version: '3.7'

services: 
    postgres:
        container_name: postgres
        image: postgres-ptbr
        build: ./postgres
        environment: 
            POSTGRES_PASSWORD: the-password
            POSTGRES_DB: the-db
        ports: 
            - "5432:5432"
        networks: 
            - the-one-network
        volumes: 
            - /home/luis/Dev/postgres_data:/var/lib/postgresql/data
    
    tenants-api-debug:
        image: tenants-api-debug
        build: ./tenants
        command: node --inspect=0.0.0.0:9229 build/index.js
        environment: 
            NODE_ENV: development
            DATABASE_URL: postgres://postgres:the-password@postgres/the-db
            PORT: 9091
        ports: 
            - "9091:9091"
        networks: 
            - the-one-network
        links: 
            - postgres
        depends_on: 
            - postgres

networks: 
    the-one-network:
        driver: bridge